id = "bit-lang"
name = "Bit"
version = "0.1.0"
description = "Bit programming language support"
authors = ["vyacheslavhere"]
schema_version = 1

[grammars.bit]
repository = "https://github.com/bit-rs/tree-sitter"
rev = "bc1a4d8131e7a7287a5bb85900e935624ea663a3"
