id = "bit-lang"
name = "Bit"
version = "0.1.0"
description = "Bit programming language support"
authors = ["vyacheslavhere"]
schema_version = 1

[grammars.bit]
repository = "https://github.com/bit-rs/tree-sitter"
rev = "ca501677f561aa70a867fe2d0737a9fd37b094c7"
